Curriculum Vitae card - jobs and skills added to in profile
solid/profile-pane pull request #10
Opened 2021-05-23 14:23 UTC by timbl

2021-05-24 13:56 UTC, angelo-v requested changes
Please add unit tests for the presenter and integration-tests for the whole CVcard. Also the build is red since 2 months which should be fixed before doing any further changes.

2021-06-06 10:52 UTC, SharonStrats requested changes
Very nice!!  I really love it!  My only comment about the look, is I'm thinking it would be nicer as the second thing.  So position 2 (swapping friends for bio). I'm not really a UX person, so just an idea.  My only other comment is about the smaller functions, it's one thing that made it hard for me to write tests before. If you are busy, I'm happy to have a go not changing the functionality.

2021-06-06 10:52 UTC, SharonStrats commented on dev/index.ts
> +// const webIdToShow = "https://timbl.inrupt.net/profile/card#me";
should we take out all the commented webIdsToShow?  Or are we just leaving them so it's easier when we are testing.

2021-06-06 10:52 UTC, SharonStrats commented on src/CVCard.ts
> +  function renderRole (role) {
I feel like we should have the function outside of the main function and just call them.  It gets us into a bit of trouble if we want to do unit testing.

2021-06-06 10:52 UTC, SharonStrats commented on src/CVCard.ts
> +const Line = (value, prefix = nothing) =>
I'm thinking it's better to leave out the comments if possible.

2021-06-06 10:52 UTC, SharonStrats commented on src/CVPresenter.ts
> +/* Just for the record this would not be a bad way to write this code in future
I think it's good in this case, because it's giving us hints what we should do in the future.

2021-06-06 10:52 UTC, SharonStrats commented on src/CVPresenter.ts
> +       orgHomePage = store.any(organization as any, ns.schema('uri'))
If we can break it down into smaller functions will have an easier time testing.

2021-06-06 10:52 UTC, SharonStrats commented on src/integration-tests/cv.spec.ts
> +  describe("without friends", () => {
did these tests not work?  I can see what I can do.

2021-06-08 11:32 UTC, merged