Add preferred pronouns
solid/profile-pane pull request #11
Opened 2021-05-25 19:51 UTC by angelo-v

2021-05-25 19:56 UTC, angelo-v commented
See https://gitter.im/solid/solidos?at=60ad54b278e1d6477d65145a

please add unit tests for the changes in presenter and add an integration test for the display of the pronouns

2021-05-25 19:58 UTC, angelo-v commented on src/presenter.ts
> +  let pronouns = store.anyJS(subject, ns.solid('preferredSubjectPronoun'), null, profile) || ''
This is all about pronouns and should be extracted to its own function with a respective name. This function could then be unit tested on its own as well

2021-06-04 07:44 UTC, SharonStrats commented on src/presenter.ts
> +  const role = store.anyValue(subject, ns.vcard("role"))
just missing a semicolon

2021-06-05 05:50 UTC, SharonStrats requested changes
It looks great!!  I tested it by changing the webid to yours.

2021-06-05 05:50 UTC, SharonStrats commented on src/presenter.ts
> +  let pronouns = store.anyJS(subject, ns.solid('preferredSubjectPronoun')) || ''
I think angelo mentioned making this a function.  The weird thing is I thought I saw the function, but I can't seem to find it.

2021-06-06 22:27 UTC, SharonStrats approved these changes
I've added a test for integration to check pronouns

2021-06-06 22:35 UTC, SharonStrats requested changes
Actually I realized we need to do 2 more tests.  I will have to add them later.

2021-06-07 11:51 UTC, SharonStrats approved these changes
Okay, got it.  integration and unit test.

2021-06-08 11:32 UTC, merged